CREATE TABLE Jokes (id INTEGER PRIMARY KEY, text TEXT);

INSERT INTO Jokes (id, text) VALUES (1, 'Quando ficar triste abrace um sapato. Um sapato com sola!');
INSERT INTO Jokes (id, text) VALUES (2, 'Como transformar um giz em cobra? Coloca o giz na água porque daí o giz bóia!');
INSERT INTO Jokes (id, text) VALUES (3, 'Por quê a velhinha não usa relógio? Porque ela é uma SENHORA!');
INSERT INTO Jokes (id, text) VALUES (4, 'Por quê o pintinho estava com o pincel? Porque ele estava PINTANDO!');
INSERT INTO Jokes (id, text) VALUES (5, 'O que é maconha enrolada em jornal? É baseado em fatos reais.');
INSERT INTO Jokes (id, text) VALUES (6, 'Por quê os dinossauros não batem palma? Porque eles já morreram.');
INSERT INTO Jokes (id, text) VALUES (7, 'Por quê os mergulhadores se jogam para trás na hora de mergulhar? Porque jogando-se para frente, cairiam dentro do barco.');
INSERT INTO Jokes (id, text) VALUES (8, 'Uma pessoa vivia terminando seus relacionamentos até que achou sua alma gêmea e nunca mais fez isso. Qual o nome do filme? O Ex-terminador.');
INSERT INTO Jokes (id, text) VALUES (9, 'O que um instrutor de auto escola foi fazer no forró? R: Ensinar Frank Aguiar.');
INSERT INTO Jokes (id, text) VALUES (10, 'O que é um Terapeuta? R: São 1024 Gigapeutas!');
INSERT INTO Jokes (id, text) VALUES (11, 'Por quê as araucárias não se perdem na mata? Pois elas tem uma pinha.');
INSERT INTO Jokes (id, text) VALUES (12, 'Por quê a araucária não foi atendida no posto de saúde? Porque não havia médico de plantão.');
INSERT INTO Jokes (id, text) VALUES (13, 'Por quê os policiais não usam sabão? Porque eles preferem detergente.');
INSERT INTO Jokes (id, text) VALUES (14, 'Qual o site do cavalinho? www.cavalinho.com.com.com.com.com');
INSERT INTO Jokes (id, text) VALUES (15, 'Qual a fórmula química da água benta? H DEUS O');
INSERT INTO Jokes (id, text) VALUES (16, 'Conhece a piada do pônei? Não. Pô nem eu.');
INSERT INTO Jokes (id, text) VALUES (17, 'O pato fala para o outro "QUACK!", o outro responde "Era exatamente o que eu ia dizer agora!"');
INSERT INTO Jokes (id, text) VALUES (18, 'Por quê a aranha é o ser mais carente do mundo? Porque é um aracNEEDYOU.');
INSERT INTO Jokes (id, text) VALUES (19, 'O que o pagodeiro foi fazer na igreja? Foi cantar PA GOD');
INSERT INTO Jokes (id, text) VALUES (20, 'Por quê Napoleão era sempre convidado para as festas? Porque ele era BON NA PARTY');
INSERT INTO Jokes (id, text) VALUES (21, 'O que aconteceu com os lápis quando souberam que o dono da Faber Castell faleceu? Ficaram desapontados');
INSERT INTO Jokes (id, text) VALUES (22, 'Para que serve óculos verde? Para verde perto');
INSERT INTO Jokes (id, text) VALUES (23, 'Para que serve óculos vermelho? Para vermelhor');
INSERT INTO Jokes (id, text) VALUES (24, 'Para que serve óculos marrom? Para ver marronmenos');
INSERT INTO Jokes (id, text) VALUES (25, 'Você sabe qual a diferença entre a lagoa e a padaria? Na lagoa há sapinho, e na padaria, assa pão.');
INSERT INTO Jokes (id, text) VALUES (26, 'Como um atomo atende o telefone? PRÓTON?!');
INSERT INTO Jokes (id, text) VALUES (27, 'Por que o Luke Skywalker escondeu seus livros? Porque ele não quer que a Princesa Leia');
INSERT INTO Jokes (id, text) VALUES (28, 'Por que dói mais tropeçar numa caixa de som? Porque amplificador');
INSERT INTO Jokes (id, text) VALUES (29, 'int x=10; int y=10; return x+y; // Qual o nome do filme? O Código dá Vinte');
INSERT INTO Jokes (id, text) VALUES (30, 'O que a esposa do Einstein disse na primeira vez que o viu nú? QUE FÍSICO!');
INSERT INTO Jokes (id, text) VALUES (31, 'Como transformar uma laranja em cobra? Esprema a laranja dentro de um saquinho, feche e faça cócegas no saquinho que daí o SUCU-RI!');
INSERT INTO Jokes (id, text) VALUES (32, 'Você sabe qual é o rei dos queijos? O Reiqueijão.');
INSERT INTO Jokes (id, text) VALUES (33, 'Por quê não roubam moto do Japonês? Por que ele compra Yamaha.');
INSERT INTO Jokes (id, text) VALUES (34, 'Quem é o Rei da Horta? O ReiPolho!');
INSERT INTO Jokes (id, text) VALUES (35, 'Quem é o Anjo do banheiro? O Anjolejo!');
INSERT INTO Jokes (id, text) VALUES (36, 'Que é o Senhor da Horta? O SeuNoura');
INSERT INTO Jokes (id, text) VALUES (37, 'Por que na Argentina as vacas vivem olhando para o céu? Porque lá tem Boi nos Ares!');
INSERT INTO Jokes (id, text) VALUES (38, 'Qual é o vinho que não deixa ninguém bêbado? Ovinho de codorna');
INSERT INTO Jokes (id, text) VALUES (39, 'Qual é o mostro grande, verde, que vive em baixo da terra e come pedras? É O Grande Monstro Verde Comedor de Pedras.');
INSERT INTO Jokes (id, text) VALUES (40, 'Qual é o animal mais justo do mundo? A cobra, porque ela não passa a perna em ninguém');
INSERT INTO Jokes (id, text) VALUES (41, 'Um matemático está preso em um freezer quadrado. O que ele faz para se salvar? Ele corre para um dos cantos, onde faz 90 graus.');
INSERT INTO Jokes (id, text) VALUES (42, 'Uma pessoa segurava uma bola azul em uma mão e uma vermelha na outra mão. Ela deixou a bola azul cair. Qual o nome do filme? Largoa Azul');
INSERT INTO Jokes (id, text) VALUES (43, 'Sabe quando os americanos comeram carne pela primeira vez? Quando chegou o Cristóvão Com lombo!');
INSERT INTO Jokes (id, text) VALUES (44, 'Um cumpadre chega na casa de outro que está assistindo TV e diz: - "E aí, cumpadi, tudo firme?" - "Não, cumpade, é Futebor."');
INSERT INTO Jokes (id, text) VALUES (45, 'Como surgiu o Chapolin? Primeiro existia o Lin... daí ele pediu para a mãe dele fazer um chá e ela fez Chapolin.' );
INSERT INTO Jokes (id, text) VALUES (46, 'Como surgiu o Moleton? O Tom criou porque ficou com ciume do MoleJerry.' );
INSERT INTO Jokes (id, text) VALUES (47, 'Estava em casa com meu vô; só tinha vagem para comer; eu não quis, mas meu Volkswagen' );
INSERT INTO Jokes (id, text) VALUES (48, 'Choco é um cachorro que só come Cacau, por isso, chocolate' );
INSERT INTO Jokes (id, text) VALUES (49, 'Se um zumbi é um morto-vivo... então ele é a prova morta que alguém morto pode ser a prova viva que há vida após a morte. ' );
INSERT INTO Jokes (id, text) VALUES (50, 'No jogo dos elétrons contra os prótons, o juiz é nêutron?' );
INSERT INTO Jokes (id, text) VALUES (51, 'Qual é o galã preferido das abelhas? O Mel Gibson!' );
INSERT INTO Jokes (id, text) VALUES (52, 'Uma pedra cumprimentou uma tora de madeira. Que horas são? Oi Tora!' );
INSERT INTO Jokes (id, text) VALUES (53, 'Qual o animal que faz os professores de inglês subirem pelas paredes? A lagarteacher' );
INSERT INTO Jokes (id, text) VALUES (54, 'O que acontece quando o jornal cai no chão? Ele quebra a coluna. ' );
INSERT INTO Jokes (id, text) VALUES (55, 'Qual o cachorro que todos nós temos no corpo? Um Beagle' );
INSERT INTO Jokes (id, text) VALUES (56, 'Triste é o manobrista, que trabalha nas horas VAGAS.' );
INSERT INTO Jokes (id, text) VALUES (57, 'Qual a cidade americana mais carente? MIAMI.' );
INSERT INTO Jokes (id, text) VALUES (58, 'Porque o jacaré tirou o jacarezinho da escola? Porque ele réptil!' );
INSERT INTO Jokes (id, text) VALUES (59, 'Eu uso casaco de pele, o Bob Dylan.' );
INSERT INTO Jokes (id, text) VALUES (60, 'Sabe quem são os inimigos dos Simpsons? Os Nãopsons.' );
INSERT INTO Jokes (id, text) VALUES (61, 'O que um etanol disse para o outro? Eita nóis!' );
INSERT INTO Jokes (id, text) VALUES (62, 'Por que o bombeiro não gosta de andar?  Porque ele so-corre.' );
INSERT INTO Jokes (id, text) VALUES (63, 'O que o Neutron diz quando o telefone toca??? Nada. Ele sempre deixa na secretária ELETRONica.' );
INSERT INTO Jokes (id, text) VALUES (64, 'O pico mais alto do mundo é o Everest. E o mais gelado? R: O picolé. ' );
INSERT INTO Jokes (id, text) VALUES (65, 'A letra "A" caiu do 2o. andar de um prédio em cima de um peixe. Qual o nome do peixe? Atum. ' );
INSERT INTO Jokes (id, text) VALUES (66, 'O mês de Junho falou para o ano: Vc jura que vc não vai acabar agora? Ele respondeu: Julho!' );
INSERT INTO Jokes (id, text) VALUES (67, 'Qual a bebida preferida das pessoas com muita cultura? É o Ya Cult.' );
INSERT INTO Jokes (id, text) VALUES (68, 'Qual é o santo protetor da pele? R: São Down.' );
INSERT INTO Jokes (id, text) VALUES (69, 'O que o sinal de - falou pro sinal de +? - Eu faço a diferença, mané!.. E o + retrucou: "E eu penso positivo, bobão!". E assim ficou tudo =.' );
INSERT INTO Jokes (id, text) VALUES (70, 'Como que a ratinha seduz seu parceiro? - Com um strip-cheese.' );
INSERT INTO Jokes (id, text) VALUES (71, '— Doutor, entendo que vocês médicos se vistam de branco. Mas por que essa luz tão forte? — Meu filho, eu sou São Pedro.' );
INSERT INTO Jokes (id, text) VALUES (72, 'Na horta, o repolho chama a couve: - Ei couve! EI COUVE! Ei, não me ouve?? / Ela responde: - Desculpe, é que eu tava ouvindo música no talo!' );
INSERT INTO Jokes (id, text) VALUES (73, 'O que é um pontinho azul no trono? Um Blu-ray!' );
INSERT INTO Jokes (id, text) VALUES (74, 'Por que o marido da Cigarra morreu? Por que ele foi fumado.' );
INSERT INTO Jokes (id, text) VALUES (75, 'Com quem você deve falar quando está desmotivado? Com o louco, porque o loucomotiva!' );
INSERT INTO Jokes (id, text) VALUES (76, 'Dois frangos estavam voando e de repente um falou: Espera aí, frango não voa. E logo em seguida caiu. Por que o outro não caiu? Por que ele era frango a passarinha' );
INSERT INTO Jokes (id, text) VALUES (77, 'Qual o animal que dá sabedoria aos cachorros? O Cãoguru.' );
INSERT INTO Jokes (id, text) VALUES (78, 'Qual o animal mais chique do mundo? O porco porque ele vive num chiqueiro' );
INSERT INTO Jokes (id, text) VALUES (79, 'Qual o animal craque de futebol? O GOLfinho.' );
INSERT INTO Jokes (id, text) VALUES (80, 'Por que a abelha morreu eletrocutada? Porque ela pousou numa rosa choque.' );
INSERT INTO Jokes (id, text) VALUES (81, 'Qual a ave que é humorista? O pinto que só vive soltando piada.' );
INSERT INTO Jokes (id, text) VALUES (82, 'Qual a galinha que quando cai fica doida? A galinha Caipira' );
INSERT INTO Jokes (id, text) VALUES (83, 'O que o rato americano falou para o rato brasileiro? Camon, dongo !' );
INSERT INTO Jokes (id, text) VALUES (84, 'Qual é a mãe da horta? A Mãe-dioca.' );
INSERT INTO Jokes (id, text) VALUES (85, 'Qual é o pai do volante? O pai-nel' );
INSERT INTO Jokes (id, text) VALUES (86, 'Todo gaúcho possui três ferramentas:O Alica-thê, o serro-tchê e o martelo. Mas pq o martelo? Porque ele ba-tchê' );
INSERT INTO Jokes (id, text) VALUES (87, 'Mamãe, que gostoso está o jantar. -Então repita filho, repita! Mamãe, que gostoso está o jantar.' );
INSERT INTO Jokes (id, text) VALUES (88, 'Qual e o doce preferido do pintinho? O Piurulito' );
INSERT INTO Jokes (id, text) VALUES (89, 'Qual e o maior sonho do pintinho escritor? Lancar seu livro de piadas' );
INSERT INTO Jokes (id, text) VALUES (90, 'Quem é o único capaz de combater o Tiranossauro Rex? O Democratossauro Tótó.' );
INSERT INTO Jokes (id, text) VALUES (91, 'Qual o cantor que dá dicas para emagrecer? O Zézé Dica Magro.' );
INSERT INTO Jokes (id, text) VALUES (92, 'Qual o apresentador de TV que comeu carne crua? Datênia.' );
INSERT INTO Jokes (id, text) VALUES (93, 'Qual a bebida preferida dos Marcianos? O chá marte.' );
INSERT INTO Jokes (id, text) VALUES (94, 'Por que o jardineiro não regou a planta? Porque ele arREGOU.' );
INSERT INTO Jokes (id, text) VALUES (95, 'Qual o herói que tem soluço? O Hulk' );
INSERT INTO Jokes (id, text) VALUES (96, 'Qual o animal que já passou da validade? O JaVALI.' );
INSERT INTO Jokes (id, text) VALUES (97, 'Nomes criativos para seus filhos gêmeos: Mateus e Mameus.' );
INSERT INTO Jokes (id, text) VALUES (98, 'Nomes criativos para seus filhos gêmeos: Nemli e Nemlerei.' );
INSERT INTO Jokes (id, text) VALUES (99, 'Nomes criativos para suas filhas gêmeas: Larissa e Larica.' );
INSERT INTO Jokes (id, text) VALUES (100, 'Nomes criativos para seus filhos gêmeos: "A"manda e "C"obedece.' );
INSERT INTO Jokes (id, text) VALUES (101, 'Qual o pais que tem mais encanadores no mundo? O Mexico, lá tem muitos mexicanos.' );
INSERT INTO Jokes (id, text) VALUES (102, 'Deixei meu Yacult cair, que Lactovacilo.' );
INSERT INTO Jokes (id, text) VALUES (103, 'Qual a miss da paciência? A mispera' );
INSERT INTO Jokes (id, text) VALUES (104, 'Por que eu fico mais atraente no inverno? Porque eu fico sensuar!' );
INSERT INTO Jokes (id, text) VALUES (105, 'O que são quatro pontos em volta do Papa? São os quatro pontos cardeais.' );
INSERT INTO Jokes (id, text) VALUES (106, 'Qual o elemento químico mais inteligente? O Oxigênio.' );
INSERT INTO Jokes (id, text) VALUES (107, 'Qual a conexão que não funciona no elevador? A conexão de escada.' );
INSERT INTO Jokes (id, text) VALUES (108, 'Por que o marinheiro a deriva gosta de assistir novela o tempo inteiro? Porque ele é um cara noVELEIRO.' );
INSERT INTO Jokes (id, text) VALUES (109, 'Onde o astrounauta caipira cuida da saúde? No spaçô.' );
INSERT INTO Jokes (id, text) VALUES (110, 'O que fazer se um tornado está vindo? Sente e espere os outro vingadores chegarem já que o THORnado chegou primeiro.' );
INSERT INTO Jokes (id, text) VALUES (111, 'Sabe por que q a chuva pegou o ônibus? Porque ela era passageira.' );
INSERT INTO Jokes (id, text) VALUES (112, 'Qual a diferença do chocolate e da economia? O choco late a econo mia.' );
INSERT INTO Jokes (id, text) VALUES (113, 'Chico tem um cachorrinho que se chama choco. Choco não fala. Chocolate.' );
INSERT INTO Jokes (id, text) VALUES (114, 'Qual o MC não bebe cerveja? o MC KeVINHO.' );
INSERT INTO Jokes (id, text) VALUES (115, 'A Abelha e o Urso: - Oi, abelha! posso ficar com isso? - Não, porque isso é mel!' );
INSERT INTO Jokes (id, text) VALUES (116, 'Por que a cantina do Elétron quebrou? Porque a massa dele é desprezível!' );
INSERT INTO Jokes (id, text) VALUES (117, 'Qual é a carne vegetariana? Contra-filé!' );
INSERT INTO Jokes (id, text) VALUES (118, 'Policial parou um carro e questionou o motorista por que o carro estava sem placa. Ele respondeu: Porque ele usa colgate total 12.' );
INSERT INTO Jokes (id, text) VALUES (119, 'O que o Thor usa para ir à um casamento? Um paliTHOR.' );
INSERT INTO Jokes (id, text) VALUES (120, 'Qual o look que pode derrotar o Darth Vader hoje? O luke do dia!' );
INSERT INTO Jokes (id, text) VALUES (121, 'Qual a bebida preferida dos dinossauros? CapuDINO.' );
INSERT INTO Jokes (id, text) VALUES (122, 'Qual o nome do cara que mora em dois endereços e faz academia? BiCEPs' );
INSERT INTO Jokes (id, text) VALUES (123, 'Qual o remédio do Ayrton Senna? Busco pan pan pan ... pan pan pan...' );
INSERT INTO Jokes (id, text) VALUES (124, 'Quando o sapato dá risada? Quando ele vê graxa!' );
INSERT INTO Jokes (id, text) VALUES (125, 'Qual a personagem dos contos de fadas é a musa inspiradora do Rap? A Bela Do MCida' );
INSERT INTO Jokes (id, text) VALUES (126, 'Qual foto das plantas que resume tudo? A foto síntese.' );
INSERT INTO Jokes (id, text) VALUES (127, 'O que o garoto químico falou para o tio quando saiu de casa? Volátil!' );
INSERT INTO Jokes (id, text) VALUES (128, 'O que o canibal vegetariano come? Batata da perna.' );
INSERT INTO Jokes (id, text) VALUES (129, 'Quem é o povo que repete tudo? os SuECOS ecos ecos ecos ecos...' );
INSERT INTO Jokes (id, text) VALUES (130, 'Qual o Rapper que mais sabe estacionar? o Mano Brando.' );
INSERT INTO Jokes (id, text) VALUES (131, 'Onde o Batman e o Robin se conheceram? No bat-papo.' );
INSERT INTO Jokes (id, text) VALUES (132, 'Qual o filósofo se sentia um lixo? O Descartes.' );
INSERT INTO Jokes (id, text) VALUES (133, 'De qual lugar do mundo os pombos surgiram?  Da Prúúúsia!' );
INSERT INTO Jokes (id, text) VALUES (134, 'Por que o lápis foi malhar? Porque ele queria ser graFITNESS' );
INSERT INTO Jokes (id, text) VALUES (135, 'Como o cantor sertanejo foi demito? Por justa calça.' );
INSERT INTO Jokes (id, text) VALUES (136, 'Qual a brincadeira preferida dos biscoitos Oreo? Caça ao tesOREO.' );
INSERT INTO Jokes (id, text) VALUES (137, 'Por que o Hitler não conseguiu invadir a Rússia? Porque ele MOSCOU.' );
INSERT INTO Jokes (id, text) VALUES (138, 'Qual a palavra que mais trabalha? O "Porque", porque ele tem 4 empregos.' );
INSERT INTO Jokes (id, text) VALUES (139, 'Qual o melhor curso para se fazer quando se está desempregado? O curso de chaveiro, pois ele abre muitas portas.' );
INSERT INTO Jokes (id, text) VALUES (140, 'O que é um ponto verde no Rio Grande do Sul? Um aBah-ca-tchê!' );
INSERT INTO Jokes (id, text) VALUES (141, 'Qual o X-Men é o melhor em propaganda publicitária? O SLogan.' );
INSERT INTO Jokes (id, text) VALUES (142, 'Qual o molho que só o gato pode comer? O CATchup.' );
INSERT INTO Jokes (id, text) VALUES (143, 'Qual o molho que só se come em Maio? Maionese.' );
INSERT INTO Jokes (id, text) VALUES (144, 'Qual o molho que é super legal? O SHOwIO.' );
INSERT INTO Jokes (id, text) VALUES (145, 'Qual o molho que não falha. Mostarda, mas não falha!' );
INSERT INTO Jokes (id, text) VALUES (146, 'O que é a fofoca? A mimiga da Babaleia!' );
INSERT INTO Jokes (id, text) VALUES (147, 'Qual a cidade que mais beija? Beijing.' );
INSERT INTO Jokes (id, text) VALUES (148, 'Por que a manicure ficou milionária? Porque ele ACETONAmegasena.' );
INSERT INTO Jokes (id, text) VALUES (149, 'O que disse o casal de Peruanos que teve filho no Réveillon? Obrigado peruano maravilhoso que tivemos!' );
INSERT INTO Jokes (id, text) VALUES (150, 'Qual o cúmulo da preguiça?  Não sei, inventa aí!' );
INSERT INTO Jokes (id, text) VALUES (151, 'Qual o cúmulo do egoísmo? Não vou dizer só eu que sei!' );
INSERT INTO Jokes (id, text) VALUES (152, 'Qual o cúmulo do esquecimento? Esquecer o dia do aniversário do irmão gêmeo!' );
INSERT INTO Jokes (id, text) VALUES (153 , 'Qual o cúmulo do esquecimento? Esquecer o dia do aniversário do irmão gêmeo!' );
INSERT INTO Jokes (id, text) VALUES (154 , 'Qual rede social que os mineiros mais usam? Uaitsap!' );
INSERT INTO Jokes (id, text) VALUES (155 , 'Qual personagem de Star Wars pega antipatia pelas pessoas? Ranço-lo!' );
INSERT INTO Jokes (id, text) VALUES (156 , 'Qual o sorvete preferido dos Vingadores? NapoliTHANOS.' );
INSERT INTO Jokes (id, text) VALUES (157 , 'Olhei para o céu e vi as estrelas formarem uma vaca, o que eu vi? Uma COWstelação!' );
INSERT INTO Jokes (id, text) VALUES (158 , 'O que piadas sobre vacas são? Muuuuuuuito boas!' );
INSERT INTO Jokes (id, text) VALUES (159 , 'Um moço se chamava Rogério, ele perdeu o RG e virou Oéio.' );
INSERT INTO Jokes (id, text) VALUES (160 , 'Qual o mês que você não quer que venha na sua casa? O NOVEMbro!' );


-- Down
DROP TABLE Jokes;
