CREATE TABLE Jokes (id INTEGER PRIMARY KEY, text TEXT);

INSERT INTO Jokes (id, text) VALUES (1, 'Quando ficar triste abrace um sapato. Um sapato com sola!');
INSERT INTO Jokes (id, text) VALUES (2, 'Como transformar um giz em cobra? Coloca o giz na água porque daí o giz bóia!');
INSERT INTO Jokes (id, text) VALUES (3, 'Por quê a velhinha não usa relógio? Porque ela é uma SENHORA!');
INSERT INTO Jokes (id, text) VALUES (4, 'Por quê o pintinho estava com o pincel? Porque ele estava PINTANDO!');
INSERT INTO Jokes (id, text) VALUES (5, 'O que é maconha enrolada em jornal? É baseado em fatos reais.');
INSERT INTO Jokes (id, text) VALUES (6, 'Por quê os dinossauros não batem palma? Porque eles já morreram.');
INSERT INTO Jokes (id, text) VALUES (7, 'Por quê os mergulhadores se jogam para trás na hora de mergulhar? Porque jogando-se para frente, cairiam dentro do barco.');
INSERT INTO Jokes (id, text) VALUES (8, 'Uma pessoa vivia terminando seus relacionamentos até que achou sua alma gêmea e nunca mais fez isso. Qual o nome do filme? O Ex-terminador.');
INSERT INTO Jokes (id, text) VALUES (9, 'O que um instrutor de auto escola foi fazer no forró? Ensinar Frank Aguiar.');
INSERT INTO Jokes (id, text) VALUES (10, 'O que é um Terapeuta? São 1024 Gigapeutas!');
INSERT INTO Jokes (id, text) VALUES (11, 'Por quê as araucárias não se perdem na mata? Pois elas tem uma pinha.');
INSERT INTO Jokes (id, text) VALUES (12, 'Por quê a araucária não foi atendida no posto de saúde? Porque não havia médico de plantão.');
INSERT INTO Jokes (id, text) VALUES (13, 'Por quê os policiais não usam sabão? Porque eles preferem detergente.');
INSERT INTO Jokes (id, text) VALUES (14, 'Qual o site do cavalinho? www.cavalinho.com.com.com.com.com');
INSERT INTO Jokes (id, text) VALUES (15, 'Qual a fórmula química da água benta? H DEUS O');
INSERT INTO Jokes (id, text) VALUES (16, 'Conhece a piada do pônei? Não. Pô nem eu.');
INSERT INTO Jokes (id, text) VALUES (17, 'O pato fala para o outro "QUACK!", o outro responde "Era exatamente o que eu ia dizer agora!"');
INSERT INTO Jokes (id, text) VALUES (18, 'Por quê a aranha é o ser mais carente do mundo? Porque é um aracNEEDYOU.');
INSERT INTO Jokes (id, text) VALUES (19, 'O que o pagodeiro foi fazer na igreja? Foi cantar PA GOD');
INSERT INTO Jokes (id, text) VALUES (20, 'Por quê Napoleão era sempre convidado para as festas? Porque ele era BON NA PARTY.');
INSERT INTO Jokes (id, text) VALUES (21, 'O que aconteceu com os lápis quando souberam que o dono da Faber Castell faleceu? Ficaram desapontados!');
INSERT INTO Jokes (id, text) VALUES (22, 'Para que serve óculos verde? Para verde perto.');
INSERT INTO Jokes (id, text) VALUES (23, 'Para que serve óculos vermelho? Para vermelhor.');
INSERT INTO Jokes (id, text) VALUES (24, 'Para que serve óculos marrom? Para ver marronmenos.');
INSERT INTO Jokes (id, text) VALUES (25, 'Você sabe qual a diferença entre a lagoa e a padaria? Na lagoa há sapinho, e na padaria, assa pão.');
INSERT INTO Jokes (id, text) VALUES (26, 'Como um atomo atende o telefone? PRÓTON?!');
INSERT INTO Jokes (id, text) VALUES (27, 'Por que o Luke Skywalker escondeu seus livros? Porque ele não quer que a Princesa Leia.');
INSERT INTO Jokes (id, text) VALUES (28, 'Por que dói mais tropeçar numa caixa de som? Porque amplificador.');
INSERT INTO Jokes (id, text) VALUES (29, 'int x=10; int y=10; return x+y; // Qual o nome do filme? O Código dá Vinte.');
INSERT INTO Jokes (id, text) VALUES (30, 'O que a esposa do Einstein disse na primeira vez que o viu nú? QUE FÍSICO!');
INSERT INTO Jokes (id, text) VALUES (31, 'Como transformar uma laranja em cobra? Esprema a laranja dentro de um saquinho, feche e faça cócegas no saquinho que daí o SUCU-RI!');
INSERT INTO Jokes (id, text) VALUES (32, 'Você sabe qual é o rei dos queijos? O Reiqueijão.');
INSERT INTO Jokes (id, text) VALUES (33, 'Por quê não roubam moto do Japonês? Por que ele compra Yamaha.');
INSERT INTO Jokes (id, text) VALUES (34, 'Quem é o Rei da Horta? O ReiPolho!');
INSERT INTO Jokes (id, text) VALUES (35, 'Quem é o Anjo do banheiro? O Anjolejo!');
INSERT INTO Jokes (id, text) VALUES (36, 'Que é o Senhor da Horta? O SeuNoura.');
INSERT INTO Jokes (id, text) VALUES (37, 'Por que na Argentina as vacas vivem olhando para o céu? Porque lá tem Boi nos Ares!');
INSERT INTO Jokes (id, text) VALUES (38, 'Qual é o vinho que não deixa ninguém bêbado? Ovinho de codorna.');
INSERT INTO Jokes (id, text) VALUES (39, 'Qual é o mostro grande, verde, que vive em baixo da terra e come pedras? É O Grande Monstro Verde Comedor de Pedras.');
INSERT INTO Jokes (id, text) VALUES (40, 'Qual é o animal mais justo do mundo? A cobra, porque ela não passa a perna em ninguém.');
INSERT INTO Jokes (id, text) VALUES (41, 'Um matemático está preso em um freezer quadrado. O que ele faz para se salvar? Ele corre para um dos cantos, onde faz 90 graus.');
INSERT INTO Jokes (id, text) VALUES (42, 'Uma pessoa segurava uma bola azul em uma mão e uma vermelha na outra mão. Ela deixou a bola azul cair. Qual o nome do filme? Largoa Azul.');
INSERT INTO Jokes (id, text) VALUES (43, 'Sabe quando os americanos comeram carne pela primeira vez? Quando chegou o Cristóvão Com lombo!');
INSERT INTO Jokes (id, text) VALUES (44, 'Um cumpadre chega na casa de outro que está assistindo TV e diz: - "E aí, cumpadi, tudo firme?" - "Não, cumpade, é Futebor."');
INSERT INTO Jokes (id, text) VALUES (45, 'Como surgiu o Chapolin? Primeiro existia o Lin... daí ele pediu para a mãe dele fazer um chá e ela fez Chapolin.');
INSERT INTO Jokes (id, text) VALUES (46, 'Como surgiu o Moleton? O Tom criou porque ficou com ciume do MoleJerry.');
INSERT INTO Jokes (id, text) VALUES (47, 'Estava em casa com meu vô; só tinha vagem para comer; eu não quis, mas meu Volkswagen');
INSERT INTO Jokes (id, text) VALUES (48, 'Choco é um cachorro que só come Cacau, por isso, chocolate');
INSERT INTO Jokes (id, text) VALUES (49, 'Se um zumbi é um morto-vivo... então ele é a prova morta que alguém morto pode ser a prova viva que há vida após a morte. ');
INSERT INTO Jokes (id, text) VALUES (50, 'No jogo dos elétrons contra os prótons, o juiz é nêutron?');
INSERT INTO Jokes (id, text) VALUES (51, 'Qual é o galã preferido das abelhas? O Mel Gibson!');
INSERT INTO Jokes (id, text) VALUES (52, 'Uma pedra cumprimentou uma tora de madeira. Que horas são? Oi Tora!');
INSERT INTO Jokes (id, text) VALUES (53, 'Qual o animal que faz os professores de inglês subirem pelas paredes? A lagarteacher');
INSERT INTO Jokes (id, text) VALUES (54, 'O que acontece quando o jornal cai no chão? Ele quebra a coluna. ');
INSERT INTO Jokes (id, text) VALUES (55, 'Qual o cachorro que todos nós temos no corpo? Um Beagle');
INSERT INTO Jokes (id, text) VALUES (56, 'Triste é o manobrista, que trabalha nas horas VAGAS.');
INSERT INTO Jokes (id, text) VALUES (57, 'Qual a cidade americana mais carente? MIAMI.');
INSERT INTO Jokes (id, text) VALUES (58, 'Porque o jacaré tirou o jacarezinho da escola? Porque ele réptil!');
INSERT INTO Jokes (id, text) VALUES (59, 'Eu uso casaco de pele, o Bob Dylan.');
INSERT INTO Jokes (id, text) VALUES (60, 'Sabe quem são os inimigos dos Simpsons? Os Nãopsons.');
INSERT INTO Jokes (id, text) VALUES (61, 'O que um etanol disse para o outro? Eita nóis!');
INSERT INTO Jokes (id, text) VALUES (62, 'Por que o bombeiro não gosta de andar?  Porque ele so-corre.');
INSERT INTO Jokes (id, text) VALUES (63, 'O que o Neutron diz quando o telefone toca??? Nada. Ele sempre deixa na secretária ELETRONica.');
INSERT INTO Jokes (id, text) VALUES (64, 'O pico mais alto do mundo é o Everest. E o mais gelado? O picolé. ');
INSERT INTO Jokes (id, text) VALUES (65, 'A letra "A" caiu do 2o. andar de um prédio em cima de um peixe. Qual o nome do peixe? Atum. ');
INSERT INTO Jokes (id, text) VALUES (66, 'O mês de Junho falou para o ano: Vc jura que vc não vai acabar agora? Ele respondeu: Julho!');
INSERT INTO Jokes (id, text) VALUES (67, 'Qual a bebida preferida das pessoas com muita cultura? É o Ya Cult.');
INSERT INTO Jokes (id, text) VALUES (68, 'Qual é o santo protetor da pele? São Down.');
INSERT INTO Jokes (id, text) VALUES (69, 'O que o sinal de - falou pro sinal de +? - Eu faço a diferença, mané!.. E o + retrucou: "E eu penso positivo, bobão!". E assim ficou tudo =.');
INSERT INTO Jokes (id, text) VALUES (70, 'Como que a ratinha seduz seu parceiro? - Com um strip-cheese.');
INSERT INTO Jokes (id, text) VALUES (71, '— Doutor, entendo que vocês médicos se vistam de branco. Mas por que essa luz tão forte? — Meu filho, eu sou São Pedro.');
INSERT INTO Jokes (id, text) VALUES (72, 'Na horta, o repolho chama a couve: - Ei couve! EI COUVE! Ei, não me ouve?? / Ela responde: - Desculpe, é que eu tava ouvindo música no talo!');
INSERT INTO Jokes (id, text) VALUES (73, 'O que é um pontinho azul no trono? Um Blu-ray!');
INSERT INTO Jokes (id, text) VALUES (74, 'Por que o marido da Cigarra morreu? Por que ele foi fumado.');
INSERT INTO Jokes (id, text) VALUES (75, 'Com quem você deve falar quando está desmotivado? Com o louco, porque o loucomotiva!');
INSERT INTO Jokes (id, text) VALUES (76, 'Dois frangos estavam voando e de repente um falou: Espera aí, frango não voa. E logo em seguida caiu. Por que o outro não caiu? Por que ele era frango a passarinha.');
INSERT INTO Jokes (id, text) VALUES (77, 'Qual o animal que dá sabedoria aos cachorros? O Cãoguru.');
INSERT INTO Jokes (id, text) VALUES (78, 'Qual o animal mais chique do mundo? O porco porque ele vive num chiqueiro.');
INSERT INTO Jokes (id, text) VALUES (79, 'Qual o animal craque de futebol? O GOLfinho.');
INSERT INTO Jokes (id, text) VALUES (80, 'Por que a abelha morreu eletrocutada? Porque ela pousou numa rosa choque.');
INSERT INTO Jokes (id, text) VALUES (81, 'Qual a ave que é humorista? O pinto que só vive soltando piada.');
INSERT INTO Jokes (id, text) VALUES (82, 'Qual a galinha que quando cai fica doida? A galinha Caipira');
INSERT INTO Jokes (id, text) VALUES (83, 'O que o rato americano falou para o rato brasileiro? Camon, dongo !');
INSERT INTO Jokes (id, text) VALUES (84, 'Qual é a mãe da horta? A Mãe-dioca.');
INSERT INTO Jokes (id, text) VALUES (85, 'Qual é o pai do volante? O pai-nel');
INSERT INTO Jokes (id, text) VALUES (86, 'Todo gaúcho possui três ferramentas:O Alica-thê, o serro-tchê e o martelo. Mas pq o martelo? Porque ele ba-tchê');
INSERT INTO Jokes (id, text) VALUES (87, 'Mamãe, que gostoso está o jantar. -Então repita filho, repita! Mamãe, que gostoso está o jantar.');
INSERT INTO Jokes (id, text) VALUES (88, 'Qual e o doce preferido do pintinho? O Piurulito');
INSERT INTO Jokes (id, text) VALUES (89, 'Qual e o maior sonho do pintinho escritor? Lancar seu livro de piadas');
INSERT INTO Jokes (id, text) VALUES (90, 'Quem é o único capaz de combater o Tiranossauro Rex? O Democratossauro Tótó.');
INSERT INTO Jokes (id, text) VALUES (91, 'Qual o cantor que dá dicas para emagrecer? O Zézé Dica Magro.');
INSERT INTO Jokes (id, text) VALUES (92, 'Qual o apresentador de TV que comeu carne crua? Datênia.');
INSERT INTO Jokes (id, text) VALUES (93, 'Qual a bebida preferida dos Marcianos? O chá marte.');
INSERT INTO Jokes (id, text) VALUES (94, 'Por que o jardineiro não regou a planta? Porque ele arREGOU.');
INSERT INTO Jokes (id, text) VALUES (95, 'Qual o herói que tem soluço? O Hulk!');
INSERT INTO Jokes (id, text) VALUES (96, 'Qual o animal que já passou da validade? O JaVALI.');
INSERT INTO Jokes (id, text) VALUES (97, 'Nomes criativos para seus filhos gêmeos: Mateus e Mameus.');
INSERT INTO Jokes (id, text) VALUES (98, 'Nomes criativos para seus filhos gêmeos: Nemli e Nemlerei.');
INSERT INTO Jokes (id, text) VALUES (99, 'Nomes criativos para suas filhas gêmeas: Larissa e Larica.');
INSERT INTO Jokes (id, text) VALUES (100, 'Nomes criativos para seus filhos gêmeos: "A"manda e "C"obedece.');
INSERT INTO Jokes (id, text) VALUES (101, 'Qual o pais que tem mais encanadores no mundo? O Mexico, lá tem muitos mexicanos.');
INSERT INTO Jokes (id, text) VALUES (102, 'Deixei meu Yacult cair, que Lactovacilo.');
INSERT INTO Jokes (id, text) VALUES (103, 'Qual a miss da paciência? A mispera');
INSERT INTO Jokes (id, text) VALUES (104, 'Por que eu fico mais atraente no inverno? Porque eu fico sensuar!');
INSERT INTO Jokes (id, text) VALUES (105, 'O que são quatro pontos em volta do Papa? São os quatro pontos cardeais.');
INSERT INTO Jokes (id, text) VALUES (106, 'Qual o elemento químico mais inteligente? O Oxigênio.');
INSERT INTO Jokes (id, text) VALUES (107, 'Qual a conexão que não funciona no elevador? A conexão de escada.');
INSERT INTO Jokes (id, text) VALUES (108, 'Por que o marinheiro a deriva gosta de assistir novela o tempo inteiro? Porque ele é um cara noVELEIRO.');
INSERT INTO Jokes (id, text) VALUES (109, 'Onde o astrounauta caipira cuida da saúde? No spaçô.');
INSERT INTO Jokes (id, text) VALUES (110, 'O que fazer se um tornado está vindo? Sente e espere os outro vingadores chegarem já que o THORnado chegou primeiro.');
INSERT INTO Jokes (id, text) VALUES (111, 'Sabe por que q a chuva pegou o ônibus? Porque ela era passageira.');
INSERT INTO Jokes (id, text) VALUES (112, 'Qual a diferença do chocolate e da economia? O choco late a econo mia.');
INSERT INTO Jokes (id, text) VALUES (113, 'Chico tem um cachorrinho que se chama choco. Choco não fala. Chocolate.');
INSERT INTO Jokes (id, text) VALUES (114, 'Qual o MC não bebe cerveja? o MC KeVINHO.');
INSERT INTO Jokes (id, text) VALUES (115, 'A Abelha e o Urso: - Oi, abelha! posso ficar com isso? - Não, porque isso é mel!');
INSERT INTO Jokes (id, text) VALUES (116, 'Por que a cantina do Elétron quebrou? Porque a massa dele é desprezível!');
INSERT INTO Jokes (id, text) VALUES (117, 'Qual é a carne vegetariana? Contra-filé!');
INSERT INTO Jokes (id, text) VALUES (118, 'Policial parou um carro e questionou o motorista por que o carro estava sem placa. Ele respondeu: Porque ele usa colgate total 12.');
INSERT INTO Jokes (id, text) VALUES (119, 'O que o Thor usa para ir à um casamento? Um paliTHOR.');
INSERT INTO Jokes (id, text) VALUES (120, 'Qual o look que pode derrotar o Darth Vader hoje? O luke do dia!');
INSERT INTO Jokes (id, text) VALUES (121, 'Qual a bebida preferida dos dinossauros? CapuDINO.');
INSERT INTO Jokes (id, text) VALUES (122, 'Qual o nome do cara que mora em dois endereços e faz academia? BiCEPs');
INSERT INTO Jokes (id, text) VALUES (123, 'Qual o remédio do Ayrton Senna? Busco pan pan pan ... pan pan pan...');
INSERT INTO Jokes (id, text) VALUES (124, 'Quando o sapato dá risada? Quando ele vê graxa!');
INSERT INTO Jokes (id, text) VALUES (125, 'Qual a personagem dos contos de fadas é a musa inspiradora do Rap? A Bela Do MCida');
INSERT INTO Jokes (id, text) VALUES (126, 'Qual foto das plantas que resume tudo? A foto síntese.');
INSERT INTO Jokes (id, text) VALUES (127, 'O que o garoto químico falou para o tio quando saiu de casa? Volátil!');
INSERT INTO Jokes (id, text) VALUES (128, 'O que o canibal vegetariano come? Batata da perna.');
INSERT INTO Jokes (id, text) VALUES (129, 'Quem é o povo que repete tudo? os SuECOS ecos ecos ecos ecos...');
INSERT INTO Jokes (id, text) VALUES (130, 'Qual o Rapper que mais sabe estacionar? o Mano Brando.');
INSERT INTO Jokes (id, text) VALUES (131, 'Onde o Batman e o Robin se conheceram? No bat-papo.');
INSERT INTO Jokes (id, text) VALUES (132, 'Qual o filósofo se sentia um lixo? O Descartes.');
INSERT INTO Jokes (id, text) VALUES (133, 'De qual lugar do mundo os pombos surgiram?  Da Prúúúsia!');
INSERT INTO Jokes (id, text) VALUES (134, 'Por que o lápis foi malhar? Porque ele queria ser graFITNESS');
INSERT INTO Jokes (id, text) VALUES (135, 'Como o cantor sertanejo foi demito? Por justa calça.');
INSERT INTO Jokes (id, text) VALUES (136, 'Qual a brincadeira preferida dos biscoitos Oreo? Caça ao tesOREO.');
INSERT INTO Jokes (id, text) VALUES (137, 'Por que o Hitler não conseguiu invadir a Rússia? Porque ele MOSCOU.');
INSERT INTO Jokes (id, text) VALUES (138, 'Qual a palavra que mais trabalha? O "Porque", porque ele tem 4 empregos.');
INSERT INTO Jokes (id, text) VALUES (139, 'Qual o melhor curso para se fazer quando se está desempregado? O curso de chaveiro, pois ele abre muitas portas.');
INSERT INTO Jokes (id, text) VALUES (140, 'O que é um ponto verde no Rio Grande do Sul? Um aBah-ca-tchê!');
INSERT INTO Jokes (id, text) VALUES (141, 'Qual o X-Men é o melhor em propaganda publicitária? O SLogan.');
INSERT INTO Jokes (id, text) VALUES (142, 'Qual o molho que só o gato pode comer? O CATchup.');
INSERT INTO Jokes (id, text) VALUES (143, 'Qual o molho que só se come em Maio? Maionese.');
INSERT INTO Jokes (id, text) VALUES (144, 'Qual o molho que é super legal? O SHOwIO.');
INSERT INTO Jokes (id, text) VALUES (145, 'Qual o molho que não falha? Mostarda, mas não falha!');
INSERT INTO Jokes (id, text) VALUES (146, 'O que é a fofoca? A mimiga da Babaleia!');
INSERT INTO Jokes (id, text) VALUES (147, 'Qual a cidade que mais beija? Beijing.');
INSERT INTO Jokes (id, text) VALUES (148, 'Por que a manicure ficou milionária? Porque ele ACETONAmegasena.');
INSERT INTO Jokes (id, text) VALUES (149, 'Qual o cúmulo da preguiça?  Não sei, inventa aí!');
INSERT INTO Jokes (id, text) VALUES (150, 'Qual o cúmulo do egoísmo? Não vou dizer só eu que sei!');
INSERT INTO Jokes (id, text) VALUES (151, 'Qual o cúmulo do esquecimento? Esquecer o dia do aniversário do irmão gêmeo!');
INSERT INTO Jokes (id, text) VALUES (152, 'Qual rede social que os mineiros mais usam? Uaitsap!');
INSERT INTO Jokes (id, text) VALUES (153, 'Qual personagem de Star Wars pega antipatia pelas pessoas? Ranço-lo!');
INSERT INTO Jokes (id, text) VALUES (154, 'Qual o sorvete preferido dos Vingadores? NapoliTHANOS.');
INSERT INTO Jokes (id, text) VALUES (155, 'Olhei para o céu e vi as estrelas formarem uma vaca, o que eu vi? Uma COWstelação!');
INSERT INTO Jokes (id, text) VALUES (156, 'O que piadas sobre vacas são? Muuuuuuuito boas!');
INSERT INTO Jokes (id, text) VALUES (157, 'Um moço se chamava Rogério, ele perdeu o RG e virou Oéio.');
INSERT INTO Jokes (id, text) VALUES (158, 'Qual o mês que você não quer que venha na sua casa? O NOVEMbro!');
INSERT INTO Jokes (id, text) VALUES (159, 'Qual o cereal favorito do vampiro? Aveia');
INSERT INTO Jokes (id, text) VALUES (160, 'Como conseguir um choquito? Colocando o dedito na tomadita!');
INSERT INTO Jokes (id, text) VALUES (161, 'Qual parte do carro foi criada no antigo Egito? Os faraóis.');
INSERT INTO Jokes (id, text) VALUES (162, 'Qual o nome da mulher que trabalha no laboratório? Ester Eliza.');
INSERT INTO Jokes (id, text) VALUES (163, 'O que dá o cruzamento de uma cobra com um porco-espinho? Um arame farpado.');
INSERT INTO Jokes (id, text) VALUES (164, 'Qual o sonho de toda cobra? Serpente.');
INSERT INTO Jokes (id, text) VALUES (165, 'Como se diz "oito" em russo? - Quasnov.');
INSERT INTO Jokes (id, text) VALUES (166, 'O que o Arnold Schwarzenegger disse quando recebeu um computador que tinha o Windows XP instalado? - Instala Vista, baby.');
INSERT INTO Jokes (id, text) VALUES (167, 'Você sabe da história da mulher que morreu de Maria? Ela foi à praia pela primeira vez, pensou que o mar vinha, só que o mar ia..');
INSERT INTO Jokes (id, text) VALUES (168, 'O marido chega em casa, bate na porta e a mulher pergunta: - Quem é? E ele responde: - Marido da Barbie!');
INSERT INTO Jokes (id, text) VALUES (169, 'O seno foi usar o banheiro, mas o cosseno tava lá dentro. Quando o seno bateu na porta, o que o cosseno gritou? TANGENTE!!!');
INSERT INTO Jokes (id, text) VALUES (170, 'Quem é a filha da Diva? Advinha!');
INSERT INTO Jokes (id, text) VALUES (171, 'Era motorista. Seu nome? José Passos Dias Aguiar.');
INSERT INTO Jokes (id, text) VALUES (172, 'O que é uma molécula?  Uma menínula muito sapécula!');
INSERT INTO Jokes (id, text) VALUES (173, 'Qual é a raça do cachorro-quente?  Hot-weiler.');
INSERT INTO Jokes (id, text) VALUES (174, 'Por que o sujeito aprendeu sozinho a contar os dias? Porque ele era autodiDATA.');
INSERT INTO Jokes (id, text) VALUES (175, 'O que são dois pontos azuis no céu?  Blueblueletas..');
INSERT INTO Jokes (id, text) VALUES (176, 'Sabe qual a diferença entre lagoinha e padaria?  Na lagoinha, há sapinho; na padaria, assa pão.');
INSERT INTO Jokes (id, text) VALUES (177, 'Se o Papai Noel morrer, ele não estará mais em trenós.');
INSERT INTO Jokes (id, text) VALUES (178, 'Na frase "proibido estacionar", qual é o sujeito?  Sujeito a guincho.');
INSERT INTO Jokes (id, text) VALUES (179, 'Qual a tecla preferida do astronauta?  Barra de Espaço!');
INSERT INTO Jokes (id, text) VALUES (180, 'O que é um ponto amarela numa Limousine?  Um MILHOnário!');
INSERT INTO Jokes (id, text) VALUES (181, 'Por que elefante não pega fogo? Porque ele já é cinza!');
INSERT INTO Jokes (id, text) VALUES (182, 'Por que os peixes comem o tempo inteiro? Porque estão sempre com água na boca!');
INSERT INTO Jokes (id, text) VALUES (183, 'o Ivo passou na faculdade de medicina e foi fazer estágio no hospital. Qual o nome do filme? O Residente IVO');
INSERT INTO Jokes (id, text) VALUES (184, 'Sabe porque o Mário pequeno é bom na fase da água? Pq ele é Marinho.');
INSERT INTO Jokes (id, text) VALUES (185, 'Qual carro que hoje é uma cicatriz? O Escort.');
INSERT INTO Jokes (id, text) VALUES (186, 'Qual o carro que foi feito especialmente para você? Parati.');
INSERT INTO Jokes (id, text) VALUES (187, 'O que é que a vaca dá depois de um terremoto? MilkShake.');
INSERT INTO Jokes (id, text) VALUES (188, 'Era uma vez um cara que tinha duas galinhas, chamadas Célia e Odi. E não gostava delas de jeito nenhum. Um belo dia, pegou duas espigas de milho, tirou-lhes o miolo, colocou em cada uma uma dinamite e jogou no galinheiro. As duas galinhas se aproximaram das espigas, comeram por um tempo, até que ambas explodiram. Qual o nome do filme? Dois milhos e bum! Odi e Célia no espaço.');
INSERT INTO Jokes (id, text) VALUES (189, 'Qual é o super-herói que usa unhas grandes? O Homem-Arranha!');
INSERT INTO Jokes (id, text) VALUES (190, 'Por que as rodas do trem são de ferro? - Porque se fossem de borracha apagariam a linha.');
INSERT INTO Jokes (id, text) VALUES (191, 'O que um jardim disse para o outro? Seu disgramado!');
INSERT INTO Jokes (id, text) VALUES (192, 'Sabe qual animal que pesava quilos e hoje em dia só pesa gramas? O es-quilo');
INSERT INTO Jokes (id, text) VALUES (193, 'Qual o cúmulo do drama? Mesmo se eu explicasse, você não me entenderia! (chorando)');
INSERT INTO Jokes (id, text) VALUES (194, 'Por que o hipertenso não pode se apaixonar? Porque a SALdade faz mal!');
INSERT INTO Jokes (id, text) VALUES (195, 'Por que chamaram o Batman para fazer um bolo? Porque só ele sabe usar a BATedeira.');
INSERT INTO Jokes (id, text) VALUES (196, 'Quando estiver sofrendo um ataque do coração, manda um BATsinal para ele vir conferir os seus BATmentos!');
INSERT INTO Jokes (id, text) VALUES (197, 'Por que a vaca foi para o espaço? Para encontrar o vácuo e ter um monte de VACUinhas e fazer a via LACTEA!');
INSERT INTO Jokes (id, text) VALUES (198, 'Diálogo: - Eu te amo! - Por que você me ama? - Toda vez que eu estou com você meu coração acelara e eu fico sem ar! - O nome disso é asma! - Então eu te ASMO muito!');
INSERT INTO Jokes (id, text) VALUES (199, 'Ao nascer e ver o mundo cruel o passarinho bradou em alta voz: "Estou chocado!"');
INSERT INTO Jokes (id, text) VALUES (200, 'Professora - Joãozinho fale uma frase com a palavra "capacidade" Joãozinho - Eu era da roça, agora eu vim morar CAPACIDADE.');
INSERT INTO Jokes (id, text) VALUES (201, 'Professora - Joãozinho fale um verbo. Joãozinho - hospedar. Professora - coloque esse verbo numa frase. Joãozinho - HOSPEDAR da bicicreta são de prástico!');
INSERT INTO Jokes (id, text) VALUES (202, 'O que o Google pai disse para o Google filho na hora do jantar? - Google Chrome!');
INSERT INTO Jokes (id, text) VALUES (203, 'O que acontece dentro do BATMAN? BATimentos.');
INSERT INTO Jokes (id, text) VALUES (204, 'O que um Pão Ranger falou para o outro Pão Ranger dentro da geladeira? Vamos MOFAR!');
INSERT INTO Jokes (id, text) VALUES (205, 'Qual o personagem da Marvel que é um pão? O BREAD pool!');
INSERT INTO Jokes (id, text) VALUES (206, 'Qual a padroeira da matemática? Madre Tereza de Calcular!');
INSERT INTO Jokes (id, text) VALUES (207, 'O que a mosca disse para as outras moscas? É noz moscada!');
INSERT INTO Jokes (id, text) VALUES (208, 'O que é um macaco com uma pasta executiva em cima de uma árvore? Um MICO-empresário!');
INSERT INTO Jokes (id, text) VALUES (209, 'O que a cabra passa quando se rala? Mééééééthiolate!');
INSERT INTO Jokes (id, text) VALUES (210, 'Como a vaca chama o namorado boi dela? Môôôôôôôôôôôôôôô!');
INSERT INTO Jokes (id, text) VALUES (211, 'Qual a melhor amiga da ovelha? a Béééééést Friend Forééééééver!');
INSERT INTO Jokes (id, text) VALUES (212, 'Um cara caiu num VÃO na estrada e gritou: Meu Deusss! Daí um pastor passou e falou: "não diga o nome de Deus em VÃO!');
INSERT INTO Jokes (id, text) VALUES (213, 'Era uma vez um homem chamado Sá... Ele não era muito bonito, mas era muito cheiroso. Ele era o Sá bonitinho cheiroso!');
INSERT INTO Jokes (id, text) VALUES (214, 'Os vingadores fizeram uma festa, mas o capitão esqueceu os doces. Ainda bem que o THORtinha!');
INSERT INTO Jokes (id, text) VALUES (215, 'Em qual país a vaca pasta mais lentamente? Na SLOWvaca!');
INSERT INTO Jokes (id, text) VALUES (216, 'Qual a fruta preferida da Cabra? A Méééélancia!');
INSERT INTO Jokes (id, text) VALUES (217, 'Por que virei Quiromante quando voltei da Alemanha? Porque lá eu aprendi a LÊ MÃO!');
INSERT INTO Jokes (id, text) VALUES (218, 'Qual o animal que vende bugingangas na rua? O Camelô!');
INSERT INTO Jokes (id, text) VALUES (219, 'Quem é o pai da aves? O PAIpagaio!');
INSERT INTO Jokes (id, text) VALUES (220, 'O que dá o cruzamento de um canguru com um urso polar? Uma bolsa térmica!');
INSERT INTO Jokes (id, text) VALUES (221, 'Qual o animal que tem fruta no nome? O JACAré!');
INSERT INTO Jokes (id, text) VALUES (222, 'Por que a vaca morreu afogada? Porque ela namorava um peixe-boi!');
INSERT INTO Jokes (id, text) VALUES (223, 'O que dá um cruzamento de um bode e uma luneta? Um bode expiatório!');
INSERT INTO Jokes (id, text) VALUES (224, 'Por que o símbolo da medicina é duas cobras enroladas? Porque se ela cura, COBRA. Se ela mata, COBRA.');
INSERT INTO Jokes (id, text) VALUES (225, 'O que é um monte de letrinhas voando? BorboLETRAS!');
INSERT INTO Jokes (id, text) VALUES (226, 'Como a ostra cai do morro? aOSTRAncos e barrancos!');
INSERT INTO Jokes (id, text) VALUES (227, 'Onde o cachorro mora? No Cãodomínio.');
INSERT INTO Jokes (id, text) VALUES (228, 'Como a cobra salva alguém de uma enchente? Dando o BOTE!');
INSERT INTO Jokes (id, text) VALUES (229, 'Quem tira a maior onda abanando a cauda? A baleia.');
INSERT INTO Jokes (id, text) VALUES (230, 'Por que as tartarugas não ficam bêbadas? Porque elas só tem casco!');
INSERT INTO Jokes (id, text) VALUES (231, 'O que o tatu mais gosta de fazer? TATUagens!');
INSERT INTO Jokes (id, text) VALUES (232, 'Qual o animal que vive engolindo sapos e não reclama? Cobras que vivem no brejo!');
INSERT INTO Jokes (id, text) VALUES (233, 'Por que as avestruzes fogem dos problemas enfiando a cabeça na terra? Porque o que os olhos não vêem o caoração não sente!');
INSERT INTO Jokes (id, text) VALUES (234, 'Por que a girafa resolveu se casar? Porque encontrou um noivo à altura!');
INSERT INTO Jokes (id, text) VALUES (235, 'Qual a cobra que é percussionista? A cascavel - ela toca chocalho!');
INSERT INTO Jokes (id, text) VALUES (236, 'Qual o cavalo do Drácula? Um puro-sangue!');
INSERT INTO Jokes (id, text) VALUES (237, 'Qual o bicho que não compra câmeras fotográficas coloridas? O Pinguim!');
INSERT INTO Jokes (id, text) VALUES (238, 'Qual o bicho que sempre anda com maquiagem? A onça pintada!');
INSERT INTO Jokes (id, text) VALUES (239, 'Qual o bicho que adora música argentina? Orango TANGO!');
INSERT INTO Jokes (id, text) VALUES (240, 'Por que o passarinho não briga com o leão? Porque ele tem PENA!');
INSERT INTO Jokes (id, text) VALUES (241, 'Por que a vaca dá leite? Porque não sabe vender!');
INSERT INTO Jokes (id, text) VALUES (242, 'Qual o animal que tem nome e sobrenome? O João de Barro!');
INSERT INTO Jokes (id, text) VALUES (243, 'Qual o passarinho detetive? O bem-te-vi!');
INSERT INTO Jokes (id, text) VALUES (244, 'O que o boi foi fazer na farmácia? Comprar um BOIcarbonato de sódio!');
INSERT INTO Jokes (id, text) VALUES (245, 'O que é um pontinho amarelo no estacionamento? Um Uno MILHO!');
INSERT INTO Jokes (id, text) VALUES (246, 'O que é um pontinho branco no acostamento da estrada? Um Uno MILHO que estacionou e virou pipoca!');
INSERT INTO Jokes (id, text) VALUES (247, 'O que é um pontinho verde na estrada? Um VolksVAGEM!');
INSERT INTO Jokes (id, text) VALUES (248, 'O que é um pontinho verde no aeroporto? Um GREENgo!');
INSERT INTO Jokes (id, text) VALUES (249, 'O que é um pontinho amarelo no céu? Um YELLOWcóptero!');
INSERT INTO Jokes (id, text) VALUES (250, 'O que é um pontinho amarelo indo em direção ao sol? Um Fandangos tentando virar Baconzitos!');
INSERT INTO Jokes (id, text) VALUES (251, 'Qual o carro do Gaúcho? o CadeTCHÊ!');
INSERT INTO Jokes (id, text) VALUES (252, 'O que é um pontinho azul no fundo da piscina? Uma ervilha prendendo a respiração!');
INSERT INTO Jokes (id, text) VALUES (253, 'O que é um pontinho vermelho no fundo da piscina? Uma ervilha tentando passar mais tempo prendendo a respiração!');
INSERT INTO Jokes (id, text) VALUES (254, 'O que é um pontinho amarelo no meio de um set de gravação? Um Jean Cloud FANDANGOS!');
INSERT INTO Jokes (id, text) VALUES (255, 'O que são oito pontinho piscando alternadamente? Uma aranha usando tênis com luzinhas!');
INSERT INTO Jokes (id, text) VALUES (256, 'O que é um pontinho vermelho na parede? Um REDlógio de parede!');
INSERT INTO Jokes (id, text) VALUES (257, 'O que é um pontinho cinza no escritório? Um GRAYpeador.');
INSERT INTO Jokes (id, text) VALUES (258, 'O que é um pontinho azul treinando artes marciais? Um BLUEce Lee');
INSERT INTO Jokes (id, text) VALUES (259, 'O que é um pontinho vermelho em cima de uma árvore? Um Morangotago!');
INSERT INTO Jokes (id, text) VALUES (260, 'O que é um pontinho roxo no céu? A super-uva!');
INSERT INTO Jokes (id, text) VALUES (261, 'O que é um pontinho amarelo surfando? RUFFLES, a batata da onda!');
INSERT INTO Jokes (id, text) VALUES (262, 'O que é um pontinho vermelho no fim do mundo? Apple-calipse!');
INSERT INTO Jokes (id, text) VALUES (263, 'O que é um pontinho marrom numa tela de cinema? O Marrom Brando!');
INSERT INTO Jokes (id, text) VALUES (264, 'O que é um pontinho preto no microscópio? Um pretozoário!');
INSERT INTO Jokes (id, text) VALUES (265, 'O que é um pontinho marrom voando? Uma BROWborleta!');
INSERT INTO Jokes (id, text) VALUES (266, 'O que é um pontinho vermelho no pântano? Um jacaRED!');
INSERT INTO Jokes (id, text) VALUES (267, 'O que é um pontinho verde na Antártida? Um pinGREEN!');
INSERT INTO Jokes (id, text) VALUES (268, 'O que é um ponto amarelo na selva? Um YELLOW-fante!');
INSERT INTO Jokes (id, text) VALUES (269, 'O que é um pontinho azul voando? Um uruBLUE!');
INSERT INTO Jokes (id, text) VALUES (270, 'O que é um pontinho vermelho na parede? Uma acerola alpinista!');
INSERT INTO Jokes (id, text) VALUES (271, 'O que é um ponto marrom no alto de uma árvore usando uma calculadora? Um Mico-computador!');
INSERT INTO Jokes (id, text) VALUES (272, 'O que é um ponto marrom no alto de uma árvore com um telefone celular? Um Mico-empresário!');
INSERT INTO Jokes (id, text) VALUES (273, 'O que é um ponto laranja no meio da selva? Um ORANGEtango!');
INSERT INTO Jokes (id, text) VALUES (274, 'O que é um ponto verde no meio da selva? Um GREENrila!');
INSERT INTO Jokes (id, text) VALUES (275, 'O que é um gigantesco ponto azul em Santa Catarina? Um BLUEmenal!');
INSERT INTO Jokes (id, text) VALUES (276, 'O que é um ponto marrom na pré-história? Um BROWNtossauro!');
INSERT INTO Jokes (id, text) VALUES (277, 'O que é um pontinho rosa no palco? PINK Floyd!');
INSERT INTO Jokes (id, text) VALUES (278, 'O que é um pontinho colorido no meio da avenida? Uma formiga fantasida para o Carnaval!');
INSERT INTO Jokes (id, text) VALUES (279, 'O que é um pontinho fazendo abdominal no Pólo Norte? O ABDOMINAvel homem da neve!');
INSERT INTO Jokes (id, text) VALUES (280, 'O que é um pontinho rosa na madeira? Um cuPINK!');
INSERT INTO Jokes (id, text) VALUES (281, 'O que é um pontinho brilhante numa vaca? Um carrapato de aparelho!');
INSERT INTO Jokes (id, text) VALUES (282, 'O que é um pontinho vermelho no castelo? A Pimenta do Reino!');
INSERT INTO Jokes (id, text) VALUES (283, 'O que é um pontinho amarelo no deserto? Um camYELLOW!');
INSERT INTO Jokes (id, text) VALUES (284, 'O que é um pontinho preto no  microscópio norte-americano? Uma BLACKtéria!');
INSERT INTO Jokes (id, text) VALUES (285, 'O que é um pontinho vermelho na TV? A RED-Globo!');
INSERT INTO Jokes (id, text) VALUES (286, 'O que é um pontinho verde na frente de um restaurante famoso? Uma LIMÃOsine!');
INSERT INTO Jokes (id, text) VALUES (287, 'O que é um pontinho marrom no carnaval de Salvador? O Carlinhos BROWN!');
INSERT INTO Jokes (id, text) VALUES (288, 'O que é um pontinho rosa cantando no palco? O Samuel ROSA!');
INSERT INTO Jokes (id, text) VALUES (289, 'O que é um pontinho marrom no Brasil em 1500? Pedro Alavares CaBROWN!');
INSERT INTO Jokes (id, text) VALUES (290, 'O que são um monte de pontinhos rosa na grama? Um PINKquenique!');
INSERT INTO Jokes (id, text) VALUES (291, 'O que é um pontinho que vai e vem no céu? Um BLUEmerangue!');
INSERT INTO Jokes (id, text) VALUES (292, 'O que é um pontinho amarelo no Titanic? YELLOWnardo de Caprio!');
INSERT INTO Jokes (id, text) VALUES (293, 'O que é são dois pontinhos na estrada? ARROZnaldinho Gaúcho dentro de seu ARROZroyce!');
INSERT INTO Jokes (id, text) VALUES (294, 'O que é o filho de um pontinho marrom no palco? Charlie BROWN Jr.!');
INSERT INTO Jokes (id, text) VALUES (295, 'O que é um pontinho preto no avião? Uma aeroMOSCA!');
INSERT INTO Jokes (id, text) VALUES (296, 'Uma pessoa sentou em cima do cachorro branco e preto, qual é o nome do filme? Sento em um dálmata.');
INSERT INTO Jokes (id, text) VALUES (297, 'O gato Tido saiu do cesto. Qual é o nome do filme? Cesto sem tido.');


-- Down
DROP TABLE Jokes;
